[colors]
background = '#0e1514'
foreground = '#dde4e2'

cursor_bg = '#81d5ca'
cursor_fg = '#0e1514'
cursor_border = '#81d5ca'

selection_bg = '#005049'
selection_fg = '#dde4e2'

ansi = ['#0e1514', '#f49c6e', '#6ad571', '#fff372', '#6acabd', '#1b6259', '#81d5ca', '#d2dfdd']
brights = ['#808a89', '#ffc09f', '#a5ffab', '#fff7a5', '#9beae0', '#b8fff5', '#d1fff9', '#f8fffe']
