use std/util "path add"

path add "~/.local/bin"
path add "~/go/bin"
path add "/opt/homebrew/bin"
path add "~/.orbstack/bin"
path add "~/scripts"
path add "~/.cargo/bin"
path add "/usr/local/bin"
path add "~/.bun/bin"
