"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:os)\
$os\
[ ](fg:os bg:os)\
$username\
[](fg:os bg:directory)\
$directory\
[](fg:directory bg:git)\
$git_branch$git_status\
[](fg:git bg:lang)\
$c$rust$golang$nodejs$php$java$kotlin$haskell$python\
[](fg:lang bg:env)\
$conda$nix_shell\
[](fg:env bg:time)\
$time\
[ ](fg:time)\
$cmd_duration\
$line_break\
$character
"""

palette = "ansi"

[palettes.ansi]
os = "1"
directory = "3"
git = "2"
lang = "6"
env = "4"
time = "5"
text = "0"

# -------------------
# OS
# -------------------
[os]
disabled = false
style = "bg:os fg:text"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

# -------------------
# USERNAME
# -------------------
[username]
show_always = false
style_user = "bg:os fg:text"
style_root = "bg:os fg:text"
format = '[ $user]($style)'

# -------------------
# DIRECTORY
# -------------------
[directory]
style = "bg:directory fg:text"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

# -------------------
# GIT
# -------------------
[git_branch]
symbol = ""
style = "bg:git"
format = '[[ $symbol $branch ](fg:text bg:git)]($style)'

[git_status]
disabled = true
style = "bg:git"
format = '[[($all_status$ahead_behind )](fg:text bg:git)]($style)'

# -------------------
# LANGUAGES
# -------------------
[nodejs]
symbol = ""
style = "bg:lang"
format = '[[ $symbol( $version) ](fg:text bg:lang)]($style)'

[c]
symbol = " "
style = "bg:lang"
format = '[[ $symbol( $version) ](fg:text bg:lang)]($style)'

[rust]
symbol = ""
style = "bg:lang"
format = '[[ $symbol( $version) ](fg:text bg:lang)]($style)'

[golang]
symbol = ""
style = "bg:lang"
format = '[[ $symbol( $version) ](fg:text bg:lang)]($style)'

[php]
symbol = ""
style = "bg:lang"
format = '[[ $symbol( $version) ](fg:text bg:lang)]($style)'

[java]
symbol = " "
style = "bg:lang"
format = '[[ $symbol( $version) ](fg:text bg:lang)]($style)'

[kotlin]
symbol = ""
style = "bg:lang"
format = '[[ $symbol( $version) ](fg:text bg:lang)]($style)'

[haskell]
symbol = ""
style = "bg:lang"
format = '[[ $symbol( $version) ](fg:text bg:lang)]($style)'

[python]
symbol = ""
style = "bg:lang"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:text bg:lang)]($style)'

# -------------------
# CONTAINERS / ENV
# -------------------
[docker_context]
symbol = ""
style = "bg:env"
format = '[[ $symbol( $context) ](fg:text bg:env)]($style)'

[conda]
symbol = "  "
style = "fg:text bg:env"
format = '[$symbol$environment ]($style)'
ignore_base = false

[nix_shell]
disabled = false
style = "fg:text bg:env"
impure_msg = "🛠️"
pure_msg = "🧪"
unknown_msg = "❓"
format = '[ $state $name ]($style)'

# -------------------
# TIME
# -------------------
[time]
disabled = false
time_format = "%R"
style = "bg:time"
format = '[[  $time ](fg:text bg:time)]($style)'

# -------------------
# CMD DURATION
# -------------------
[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "bg:time"
disabled = false
show_notifications = true
min_time_to_notify = 45000

# -------------------
# LINE BREAK / PROMPT
# -------------------
[line_break]
disabled = false

[character]
disabled = true
success_symbol = '[❯](bold fg:lang)'
error_symbol = '[❯](bold fg:os)'
vimcmd_symbol = '[❮](bold fg:lang)'
vimcmd_replace_one_symbol = '[❮](bold fg:time)'
vimcmd_replace_symbol = '[❮](bold fg:time)'
vimcmd_visual_symbol = '[❮](bold fg:directory)'
