#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: $0 <command to run>"
    exit 1
fi

command_to_run="$@"
pid=""

run_command() {
    if [ ! -z "$pid" ]; then
        kill $pid
        wait $pid 2>/dev/null
    fi
    echo "---------------"
    eval "$command_to_run" &
    pid=$!
}

run_command  

while inotifywait -qq -r -e modify,create,delete,move --exclude '(^|/)\.[^/]+$' ./; do
    run_command
done
