.PHONY: all
all:
	stow --target=$$HOME aerospace
	stow --target=$$HOME fish
	stow --target=$$HOME git
	stow --target=$$HOME hypr
	stow --target=$$HOME niri
	stow --target=$$HOME nushell
	stow --target=$$HOME nvim
	stow --target=$$HOME starship
	stow --target=$$HOME wezterm
	stow --target=$$HOME zellij
	stow --target=$$HOME zsh

.PHONY: delete
delete:
	stow -D aerospace
	stow -D fish
	stow -D git
	stow -D hypr
	stow -D niri
	stow -D nushell
	stow -D nvim
	stow -D starship
	stow -D wezterm
	stow -D zellij
	stow -D zsh
